services:
  - type: web
    name: face-attendance-backend
    env: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_attendance_app:app --host 0.0.0.0 --port 10000

